name: On version drafted

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Build JARs
        run: ./gradlew build

  upload:
    runs-on: ubuntu-latest
    needs: build
    env:
      REPOSITORY_ID: java-repo
      LOCATION: northamerica-northeast1
      PROJECT_ID: empire-stage-registry
      SERVICE_ACCOUNT: ghasvcacct@empire-stage-registry.iam.gserviceaccount.com
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          server-id: github
          settings-path: ${{ github.workspace }}
      - id: auth-publish
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_NON_PROD_DOCKER_AUTH }}
      - name: gcloud config
        run: |
          gcloud config set artifacts/repository $REPOSITORY_ID
          gcloud config set artifacts/location $LOCATION
          gcloud config set account $SERVICE_ACCOUNT
          gcloud auth activate-service-account $SERVICE_ACCOUNT --key-file=$GOOGLE_APPLICATION_CREDENTIALS --project=$PROJECT_ID
      - name: delete previous upload
        continue-on-error: true
        run: |
          sed 's/kotlin.code.style/noop/' gradle.properties > /tmp/.env && source /tmp/.env
          gcloud artifacts versions delete $version --package=ca.empire.pu:processingunit --quiet
          gcloud artifacts versions delete $version --package=ca.empire.pu:kafkaplugin --quiet
          gcloud artifacts versions delete $version --package=ca.empire.pu:open-telemetry --quiet
          gcloud artifacts versions delete $version --package=ca.empire.pu:pubsubplugin --quiet
          gcloud artifacts versions delete $version --package=ca.empire.pu:monitorplugin --quiet
      - name: Publish with Gradle
        run: ./gradlew publish
